server:
  port: 9080
  context-path: /note-service

security:
  basic:
   enabled: true
#  user:
#    name: testuser
#    password: testuser
  
    
management:
  security:
    enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notedb
    username: root
    password: passcode
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    